### ISSUE TITLE
"make SkylakeX/K12Tests" results in errors

### ISSUE THREAD

**Issue by mdnahas** [XKCP/K12#3]
Running "make SkylakeX/K12Tests" resulted in errors.   (Running "make generic64/K12Tests" works fine.)

First error:
In file included from /usr/lib/gcc/x86_64-linux-gnu/9/include/immintrin.h:55,
                 from lib/OptimizedAVX512/KeccakP-1600-times2-SIMD512.c:22:
/usr/lib/gcc/x86_64-linux-gnu/9/include/avx512fintrin.h:7415:1: error: inlining failed in call to always_inline ‘_mm512_xor_si512’: target specific option mismatch
 7415 | _mm512_xor_si512 (__m512i __A, __m512i __B)
      | ^~~~~~~~~~~~~~~~

I'm on Ubuntu 19.10.  
$ cc --version
cc (Ubuntu 9.2.1-9ubuntu2) 9.2.1 20191008
$gcc --version
gcc (Ubuntu 9.2.1-9ubuntu2) 9.2.1 20191008

Complete output from "make SkylakeX/K12Tests > errors_SkylakeX_K12Tests.txt 2>&1" is attached.

[errors_SkylakeX_K12Tests.txt](https://github.com/XKCP/K12/files/4105530/errors_SkylakeX_K12Tests.txt)

**Comment by gvanas** [comment]
I'll have a look in the coming days. (I currently don't have access to my AXV512 machine.)

Just to make sure: Does the machine that you are compiling on support AVX512?

**Comment by mdnahas** [comment]
The interwebs said this command would identify my core:
$ cat /sys/devices/cpu/caps/pmu_name
skylake

From that, I tried the target "SkylakeX/K12Tests".   Looking at Wikipedia pages, it seems "Skylake" and "Skylake-X" are different processors and only Skylake-X has AVX512.

When I search for the AVX-512 cpu flags ("lscpu | grep avx512"), I get nothing.

It looks like I don't have support for AVX-512.  I tried "make Haswell/K12Tests" and that worked fine.  I ran the generic and Haswell test and it looks like the AVX (non-512) is being detected and used.  Haswell runs about 4 times faster than generic.  Output follows if you care.

I will close this issue.  It was user error, but you might see if there is something you can do to guide users.  Perhaps it can generate a better error message when the headers aren't around?  Or, maybe the webpage can have the commands to detect the flags?  ("lscpu | grep avx" and "lscpu | grep avx512")   I'd also recommend changing the names from "SkylakeX" and "Haswell" - those may mean something to a CPU architect, but it was hard for me as a user to pick which one I was supposed to use.  Maybe call them AVX and AVX512?  


$ Haswell/K12Tests --speed
*** KangarooTwelve ***
Using Keccak-p[1600,12] implementations:
- ×1: AVX2 optimized implementation
      + KeccakP1600_12rounds_FastLoop_Absorb()
- ×2: 128-bit SIMD implementation (SSE2, 2 rounds unrolled)
- ×4: 256-bit SIMD implementation (AVX2, 12 rounds unrolled)
      + KeccakP1600times4_12rounds_FastLoop_Absorb()
- ×8: not used
...
  532480 bytes:    462480 cycles,  0.869 cycles/byte

For comparison:
$ generic64/K12Tests --speed
*** KangarooTwelve ***
Using Keccak-p[1600,12] implementations:
- ×1: generic 64-bit optimized implementation (all rounds unrolled)
      + KeccakP1600_12rounds_FastLoop_Absorb()
- ×2: not used
- ×4: not used
- ×8: not used
...
  532480 bytes:   1072344 cycles,  2.014 cycles/byte

**Comment by gvanas** [comment]
Thanks for the suggestions!

What kind of machine do you have? 0.87 cycles/byte with AVX2 looks rather fast.

**Comment by mdnahas** [comment]
My laptop is a Dell XPS 13, model 9370.
The processor is "Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz"
It has 4 CPUs, with 2 hyperthreads per CPU.

Wikichip has a [page on the processor](https://en.wikichip.org/wiki/intel/core_i5/i5-8250u).  "Kaby Lake" microarchitecture, if that means anything.  

"lscpu" output below.



$ lscpu
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
Address sizes:                   39 bits physical, 48 bits virtual
CPU(s):                          8
On-line CPU(s) list:             0-7
Thread(s) per core:              2
Core(s) per socket:              4
Socket(s):                       1
NUMA node(s):                    1
Vendor ID:                       GenuineIntel
CPU family:                      6
Model:                           142
Model name:                      Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz
Stepping:                        10
CPU MHz:                         1045.421
CPU max MHz:                     3400.0000
CPU min MHz:                     400.0000
BogoMIPS:                        3600.00
Virtualization:                  VT-x
L1d cache:                       128 KiB
L1i cache:                       128 KiB
L2 cache:                        1 MiB
L3 cache:                        6 MiB
NUMA node0 CPU(s):               0-7
Vulnerability Itlb multihit:     KVM: Mitigation: Split huge pages
Vulnerability L1tf:              Mitigation; PTE Inversion; VMX conditional cache flushes, SMT vulnerable
Vulnerability Mds:               Mitigation; Clear CPU buffers; SMT vulnerable
Vulnerability Meltdown:          Mitigation; PTI
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl and seccomp
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Full generic retpoline, IBPB conditional, IBRS_FW, STIBP conditional, RSB filling
Vulnerability Tsx async abort:   Not affected
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxs
                                 r sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_
                                 good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx est tm2
                                  ssse3 sdbg fma cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsa
                                 ve avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb invpcid_single pti ssbd ibrs ibpb s
                                 tibp tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms i
                                 nvpcid mpx rdseed adx smap clflushopt intel_pt xsaveopt xsavec xgetbv1 xsaves dtherm ida arat pl
                                 n pts hwp hwp_notify hwp_act_window hwp_epp md_clear flush_l1d
